spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeying_social?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: naQRLdDPbGv2j7PX_
  data:
    redis:
      host: localhost
      port: 6379
      password: PmEpfRjpBnTN6CgW

minio:
  endpoint: http://127.0.0.1:9001 #内网地址
  domain: https://social.yeying.pub/file  #外网访问地址
  accessKey: admin
  secretKey: 3fBSt6AkgFuD77D6
  bucketName: yeying-social
  imagePath: image
  filePath: file
  videoPath: video
  expireIn: 180 # 文件过期时间,单位:天
