spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeying_social?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379

minio:
  endpoint: http://127.0.0.1:9000 #内网地址
  domain: http://127.0.0.1:9000  #外网访问地址
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: yeying-social
  imagePath: image
  filePath: file
  videoPath: video
  expireIn: 180 # 文件过期时间,单位:天
